export const breakpoints = {
  compact: 480,
  medium: 768,
  wide: 1024,
  canvas: 1440,
} as const;

export type BreakpointName = keyof typeof breakpoints;

export const responsiveImageSizes = {
  fullBleed: '100vw',
  productGrid:
    '(max-width: 47.999rem) 100vw, (max-width: 63.999rem) 50vw, 33vw',
  footerArtwork: '(max-width: 47.999rem) 80vw, 484px',
  avatar: '40px',
  icon: '38px',
  brandMark: '26px',
} as const;

export const designTokenCssVariables = [
  '--hb-color-ink',
  '--hb-color-text-muted',
  '--hb-color-surface',
  '--hb-color-surface-muted',
  '--hb-color-border',
  '--hb-color-border-strong',
  '--hb-color-brand',
  '--hb-color-brand-hover',
  '--hb-color-brand-soft',
  '--hb-color-danger',
  '--hb-color-danger-soft',
  '--hb-color-warning',
  '--hb-color-success',
  '--hb-color-text-inverse',
  '--hb-font-sans',
  '--hb-font-serif',
  '--hb-font-size-xs',
  '--hb-font-size-sm',
  '--hb-font-size-base',
  '--hb-font-size-lg',
  '--hb-font-size-xl',
  '--hb-font-size-display',
  '--hb-line-height-tight',
  '--hb-line-height-normal',
  '--hb-line-height-relaxed',
  '--hb-space-1',
  '--hb-space-2',
  '--hb-space-3',
  '--hb-space-4',
  '--hb-space-6',
  '--hb-space-8',
  '--hb-space-12',
  '--hb-space-16',
  '--hb-space-24',
  '--hb-radius-sm',
  '--hb-radius-md',
  '--hb-radius-lg',
  '--hb-radius-round',
  '--hb-radius-pill',
  '--hb-shadow-sm',
  '--hb-shadow-md',
  '--hb-focus-ring',
  '--hb-duration-fast',
  '--hb-duration-normal',
  '--hb-layout-canvas',
  '--hb-layout-content',
  '--hb-layout-reading',
  '--hb-page-gutter',
  '--hb-breakpoint-compact',
  '--hb-breakpoint-medium',
  '--hb-breakpoint-wide',
  '--hb-breakpoint-canvas',
] as const;
