**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!apps/
!apps/api/
!apps/api/**
!apps/api-migrate/
!apps/api-migrate/**

!packages/
!packages/auth-contract/
!packages/auth-contract/**
!packages/typescript-config/
!packages/typescript-config/**

**/.env
**/.env.*
!**/.env.example
**/.turbo
**/coverage
**/dist
**/node_modules
**/test-results
**/*.spec.ts
**/*.test.ts
**/*.tsbuildinfo
apps/api/README.md
apps/api/scripts
!apps/api/scripts/
!apps/api/scripts/provision-local-admin.ts
apps/api/src/generated
apps/api/test
